### ISSUE TITLE
Remove rem?

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-tabs#1]
With the last update we added rem units. However, anyone that using the old version is seeing changes in how the tabs are displayed.

If the font-size isn't specified on html, the tabs overlap oddly so it has to be added.

``` css
html {
  font-size: 62.5%;
}
```
