### ISSUE TITLE
Tab styling

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-tabs#14]
We fixed some tab styling in RM, but not in the main plugin.

I'd recommend this instead of https://github.com/copyblogger/genesis-tabs/pull/5
```css
.ui-tabs ul.ui-tabs-nav li {
	display: inline-block;
	list-style-type: none;
	margin: 0 5px -3px 0;
	padding: 5px 0;
	text-align: center;
}

.ui-tabs ul.ui-tabs-nav li::before {
	content: "";
	padding: 0;
}
```
